.TH FASDA 1
.SH NAME    \" Section header
.PP

fasda - Fast, simple differential analysis

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na 
fasda abundance features.gff3 alignment-file [alignment-file ...]
fasda normalize [--mrn] [--output file.tsv] abundance1.tsv abundance2.tsv ...
fasda [--output file.txt] abundance1.tsv abundance2.tsv [abudance3.tsv...]
.ad
.fi

\" Optional sections
.SH "DESCRIPTION"

.B FASDA
is a set of fast, simple differential analysis tools written in C for
maximum speed, portability, and easy command-line use.

.SH "SEE ALSO"
fasda-abundance(1), fasda-normalize(1), fasda-fold-change(1)

.SH BUGS
Please report bugs to the author and send patches in unified diff format.
(man diff for more information)

.SH AUTHOR
.nf
.na
J. Bacon
