.TH DIFFANAL 1
.SH NAME    \" Section header
.PP

diffanal - Fast and easy differential analysis

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na 
diffanal reference alignment-files
.ad
.fi

.SH OPTIONS
.TP
\fB\-\-\flagfR[=\fIparameter\fR]
description

\" Optional sections
.SH "HOW TO READ THIS MANUAL"
.SH "ORGANIZATION"
.SH "PURPOSE"
.SH "DESCRIPTION"

.SH FILES
.nf
.na
    \" List related files and describe each one here
.ad
.fi

.SH ENVIRONMENT
.nf
.na
    \" List related environment variables and describe each one here
.ad
.fi

.SH "SEE ALSO"
    \" List related commands here

.SH BUGS
Please report bugs to the author and send patches in unified diff format.
(man diff for more information)

.SH AUTHOR
.nf
.na

