.TH DIFFANAL-FOLD-CHANGE 1
.SH NAME    \" Section header
.PP

diffanal fold-change - Compute fold-change and P-values from normalized
counts

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na 
diffanal fold-change [--output file.txt] \\
    normalized-counts1.tsv  normalized-counts2.tsv \\
    [normalized-counts3.tsv ...]
.ad
.fi

.SH OPTIONS
.TP
\fB--output\fR file.txt
Report fold-change and P-values to file.txt instead of the default stdout.

.SH "DESCRIPTION"

.B diffanal fold-change
computes fold-change and P-values for two or more conditions.  The input
is two or more tab-separated values (TSV) files containing normalized
counts for all conditions.  These files are generally produced by
.B diffanal normalize.

Currently, the Mann-Whitney U-test (A.K.A. Wilcoxon rank sum test) is used
to compute P-value and this requires a minimum of 8 replicates per condition
to achieve reasonable statistical power.  Future versions may include
parametric tests that can provide power with fewer replicates, and the
expense of high FDR (false discovery rate).

.SH FILES
.nf
.na
abundance.tsv: Input with normalized counts for all replicates of 1 condition
file.txt: Output containing fold-change and P-values
.ad
.fi

.SH "SEE ALSO"
diffanal-abundance(1), diffanal-normalize(1)

.SH BUGS
Please report bugs to the author and send patches in unified diff format.
(man diff for more information)

.SH AUTHOR
.nf
.na
J. Bacon
