.TH DIFFANAL-ABUNDANCE 1
.SH NAME    \" Section header
.PP

diffanal abundance - Compute abundances from SAM data

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na 
diffanal abundance features.gff3 alignment-file [alignment-file ...]
.ad
.fi

.SH "DESCRIPTION"
.B "diffanal abundance"
computes raw read counts from one or more SAM/BAM/CRAM files overlapping
each features in a GFF3 file.  Output is an abundance.tsv file in the
same format as those produced by kallisto.

Abundances in the output are raw counts of properly paired reads that are
not flagged as secondary alignments, failed QC, duplicate, or supplementary.
For paired-end reads, both mates are counted separately, so the counts
should be expected to reflect about double the number of fragments aligned.

Any normalization of counts is left to downstream tools such as
.B diffanal-normalize(1).

.SH FILES
.nf
.na
features.gff3
alignment.bam
.ad
.fi

.SH "SEE ALSO"
diffanal-normalize(1), diffanal-fold-change(1)

.SH BUGS
Please report bugs to the author and send patches in unified diff format.
(man diff for more information)

.SH AUTHOR
.nf
.na
J. Bacon
