
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Mutator functions for setting with no sanity checking.  Use these to
 *  set structure members from functions outside the bl_alignment_stats_t
 *  class.  These macros perform no data validation.  Hence, they achieve
 *  maximum performance where data are guaranteed correct by other means.
 *  Use the mutator functions (same name as the macro, but lower case)
 *  for more robust code with a small performance penalty.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

/* temp-alignment-stats-mutators.c */
int bl_alignment_stats_set_total(bl_alignment_stats_t *bl_alignment_stats_ptr, unsigned long new_total);
int bl_alignment_stats_set_overlapping(bl_alignment_stats_t *bl_alignment_stats_ptr, unsigned long new_overlapping);
