    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the bl_alignment_stats_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define BL_ALIGNMENT_STATS_TOTAL(ptr)   ((ptr)->total)
#define BL_ALIGNMENT_STATS_OVERLAPPING(ptr) ((ptr)->overlapping)
