/***************************************************************************
 *  This file is automatically generated by gen-get-set.  Be sure to keep
 *  track of any manual changes.
 *
 *  These generated functions are not expected to be perfect.  Check and
 *  edit as needed before adding to your code.
 ***************************************************************************/

#include <string.h>
#include <ctype.h>
#include <stdbool.h>        // In case of bool
#include <stdint.h>         // In case of int64_t, etc
#include <xtend/string.h>   // strlcpy() on Linux
#include "alignment-stats.h"


/***************************************************************************
 *  Library:
 *      #include <biolibc/alignment-stats.h>
 *      -lbiolibc -lxtend
 *
 *  Description:
 *      Mutator for total member in a bl_alignment_stats_t structure.
 *      Use this function to set total in a bl_alignment_stats_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      total is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      bl_alignment_stats_ptr Pointer to the structure to set
 *      new_total       The new value for total
 *
 *  Returns:
 *      BL_DATA_OK if the new value is acceptable and assigned
 *      BL_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      bl_alignment_stats_t bl_alignment_stats;
 *      unsigned long   new_total;
 *
 *      if ( bl_alignment_stats_set_total(&bl_alignment_stats, new_total)
 *              == BL_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2022-04-10  gen-get-set Auto-generated from alignment-stats.h
 ***************************************************************************/

int     bl_alignment_stats_set_total(bl_alignment_stats_t *bl_alignment_stats_ptr, unsigned long new_total)

{
    if ( false )
	return BL_DATA_OUT_OF_RANGE;
    else
    {
	bl_alignment_stats_ptr->total = new_total;
	return BL_DATA_OK;
    }
}


/***************************************************************************
 *  Library:
 *      #include <biolibc/alignment-stats.h>
 *      -lbiolibc -lxtend
 *
 *  Description:
 *      Mutator for overlapping member in a bl_alignment_stats_t structure.
 *      Use this function to set overlapping in a bl_alignment_stats_t object
 *      from non-member functions.  This function performs a direct
 *      assignment for scalar or pointer structure members.  If
 *      overlapping is a pointer, data previously pointed to should
 *      be freed before calling this function to avoid memory
 *      leaks.
 *
 *  Arguments:
 *      bl_alignment_stats_ptr Pointer to the structure to set
 *      new_overlapping The new value for overlapping
 *
 *  Returns:
 *      BL_DATA_OK if the new value is acceptable and assigned
 *      BL_DATA_OUT_OF_RANGE otherwise
 *
 *  Examples:
 *      bl_alignment_stats_t bl_alignment_stats;
 *      unsigned long   new_overlapping;
 *
 *      if ( bl_alignment_stats_set_overlapping(&bl_alignment_stats, new_overlapping)
 *              == BL_DATA_OK )
 *      {
 *      }
 *
 *  See also:
 *      (3)
 *
 *  History: 
 *  Date        Name        Modification
 *  2022-04-10  gen-get-set Auto-generated from alignment-stats.h
 ***************************************************************************/

int     bl_alignment_stats_set_overlapping(bl_alignment_stats_t *bl_alignment_stats_ptr, unsigned long new_overlapping)

{
    if ( false )
	return BL_DATA_OUT_OF_RANGE;
    else
    {
	bl_alignment_stats_ptr->overlapping = new_overlapping;
	return BL_DATA_OK;
    }
}
