fc-ge.o: fc-ge.c pval.h
	${CC} -c ${CFLAGS} fc-ge.c

mann-whitney.o: mann-whitney.c
	${CC} -c ${CFLAGS} mann-whitney.c

pval.o: pval.c pval.h
	${CC} -c ${CFLAGS} pval.c

save-pval.o: save-pval.c pval.h
	${CC} -c ${CFLAGS} save-pval.c

