exact-p-val.o: exact-p-val.c pval.h
	${CC} -c ${CFLAGS} exact-p-val.c

fc-ge.o: fc-ge.c pval.h
	${CC} -c ${CFLAGS} fc-ge.c

mann-whitney.o: mann-whitney.c
	${CC} -c ${CFLAGS} mann-whitney.c

pval-sim.o: pval-sim.c pval.h
	${CC} -c ${CFLAGS} pval-sim.c

